# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in package.json
RUN yarn

# Make port 3000 available to the world outside this container
EXPOSE 5173

# Run the command to start the app
CMD ["yarn", "start"]